# Generated by Django 6.0.3 on 2026-04-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_slug'),
        ('catalog', '0007_product_slug_alter_category_slug'),
    ]

    operations = [
    ]
